### ISSUE TITLE
Can I use SqliteCreateDatabaseIfNotExists within an external transaction?

### ISSUE THREAD

**Issue by unageek** [msallin/SQLiteCodeFirst#139]
I want to use `SqliteCreateDatabaseIfNotExists` within a transaction, but I can't because `SqliteInitializerBase.InitializeDatabase()` creates one while execution. Is there any way to use an external transaction with the initializer?

**Comment by msallin** [comment]
Hi

`SqliteCreateDatabaseIfNotExists`  inherits from  `SqliteInitializerBase`.
The method `InitializeDatabase` is marked as virtual.
You can inherit either from `SqliteCreateDatabaseIfNotExists` and implement your own logic for the `InitializeDatabase`-Method.

Maybe the simplest way is just to copy the code from the base class and adjust it for your needs.

https://github.com/msallin/SQLiteCodeFirst/blob/a5f2217bc1d757bb86a56a4bd06a92e66b594100/SQLite.CodeFirst/Public/DbInitializers/SqliteInitializerBase.cs#L73

**Comment by unageek** [comment]
@msallin Thank you for your response! Yes, that should solve the problem. However, as `InMemoryAwareFile` is internal, I have to do more copy-and-paste to support both file and in-memory database.

As an alternative, I've created PR #140. Could you please take a look at that?

**Comment by msallin** [comment]
Thank you for your PR. As I look at this, I ask myself whether the first transaction is necessary.
The first transaction is to ensure the atomicity of the Database creation.
Inside this transaction the `SqliteDatabaseCreator` is called.
There I wrote the following code:
`db.ExecuteSqlCommand(TransactionalBehavior.EnsureTransaction, sql);`
That this query will always be executed as transaction (either as a new one or the existing will be used).
That means also, that your code will not work (there will always be a transaction, which is IMHO how it should be). 

The solution here is simply to remove the first transaction creation in the initializer.
-> The query will be executed always inside a transaction but you can specify your own.

Then there is the second part, the seeding of the data.
There its also not necessary to have explicitly a transaction because SaveChanges is only called once, which means there is an implicit transaction.

Therefore, I'll reject your PR and just delete the unnecessary code. It would be great if you can test your use case with it.

**Comment by msallin** [comment]
Here we go..

Source: https://github.com/msallin/SQLiteCodeFirst/tree/%23139
Assemblies & NuGet: https://ci.appveyor.com/project/msallin/sqlitecodefirst/build/job/1edxis7dqpns9qda/artifacts

**Comment by unageek** [comment]
@msallin Thank you very much for the investigation, the modified initializer worked perfectly. That should be the best solution.

Please close this issue as soon as the code gets merged.

**Comment by msallin** [comment]
Version 1.5.2 published. NuGet will list it within one hour.
