### ISSUE TITLE
Always create missing tables?

### ISSUE THREAD

**Issue by ideka** [msallin/SQLiteCodeFirst#170]
I don't need complicated migration support, tables existing in my database will not be modified. But sometimes, new tables need to be added.

As far as I understand, by default the database is created along with all tables only once and only if the database doesn't exist. Is it possible to make it so tables that exist in the model but not the database are detected and created automatically as well?

**Comment by msallin** [comment]
You can implement your own initializer (https://github.com/msallin/SQLiteCodeFirst/tree/master/SQLite.CodeFirst/Public/DbInitializers).

However, that enables you to create the database using the code-first approach initially, but it will become more complex. My generator generates the necessary SQL code for the whole Database as a string. Moreover, your tables may have relationships and constraints. Depending on your needs, you may look at this https://github.com/msallin/SQLiteCodeFirst/issues/4 or you use my generator and work on text level (e.g. diff and manipulate the string - take inspiration from here https://github.com/msallin/SQLiteCodeFirst/blob/master/SQLite.CodeFirst/Public/DbInitializers/SqliteDropCreateDatabaseWhenModelChanges.cs). 

Does that help?

**Comment by tbayart** [comment]
> I don't need complicated migration support, tables existing in my database will not be modified. But sometimes, new tables need to be added.

This is what is called migration.

> As far as I understand, by default the database is created along with all tables only once and only if the database doesn't exist. 

This is not true, all the behaviors depends on your needs.
The best approach is code-first, and like your code/application, your database must be versionned.
Version **x** you have a missing table that need to be added.
Version **x+1** the missing table was added.
Between those two steps is the purpose of versionning and migration.

> Is it possible to make it so tables that exist in the model but not the database are detected and created automatically as well?

Doing so is outside of ORM scope like this one because ORMs does not write conditionnal code.
Their purpose is to map your data model with your code, not maintain the data structure.
If you want to upgrade your database from code with an ORM like SQLiteCodeFirst, your in-code data structure must reflect your database structure, using versionning and migration you can easily reach your goal.

If you want to perform database upgrade by analysing your database structure and compare it with a target structure or list of table, you have to write the whole engine.
I don't know any ORM with this capability, even less able to target multiple SQL engines/technologies.

Like i always say, everything is possible in developement, the main variable is the time which grow exponentially with the complexity.
What you are asking is technically more complicated than simple migration.

**Comment by ideka** [comment]
@tbayart I appreciate the contribution but that's a tad too complex to consider for my needs.

@msallin Okay, it's hackish but I was able to come up with this, which works and it's all I really need:
```cs
private class CreateMissingTables<TContext> : SqliteCreateDatabaseIfNotExists<TContext>
    where TContext : DbContext
{
    public CreateMissingTables(DbModelBuilder modelBuilder, bool nullByteFileMeansNotExisting)
        : base(modelBuilder, nullByteFileMeansNotExisting) { /* NOOP */ }

    public CreateMissingTables(DbModelBuilder modelBuilder)
        : base(modelBuilder, false) { /* NOOP */ }

    public override void InitializeDatabase(TContext context)
    {
        base.InitializeDatabase(context);

        var model = ModelBuilder.Build(context.Database.Connection);
        var sqliteSqlGenerator = new SqliteSqlGenerator(DefaultCollation);
        string original = sqliteSqlGenerator.Generate(model.StoreModel);

        string final = "";
        foreach (var line in original.Split('\n'))
        {
            const string CreateTable = "CREATE TABLE ";
            if (!line.Trim().StartsWith(CreateTable))
                continue;
            final += $"CREATE TABLE IF NOT EXISTS {line.Trim().Substring(CreateTable.Length)}\n";
        }

        context.Database.ExecuteSqlCommand(TransactionalBehavior.EnsureTransaction, final);
        context.SaveChanges();
    }
}
```

Thanks for the pointers.

**Comment by msallin** [comment]
Glad to see that you were able to solve your problem!
