### ISSUE TITLE
NuGet package incorrect net45

### ISSUE THREAD

**Issue by inovadev** [msallin/SQLiteCodeFirst#19]
Good stuff, but I have to recompile your source code for .net 4.5.
It seems both net45 and net452 in your package are targeting .net 4.5.2.
Hopefully you can fix this at your earliest convenience.

Thanks so much.

**Comment by msallin** [comment]
Hi 
I'm working on this.
As you see, there is a new branch which contains the configuration to build the same code against .net 4.0 and .net 4.5. Now I need to figure out how to run a build for multiple configurations in only one job, so that I can build the NuGet Package (I'm using Appveyor for CI and CD).

https://github.com/msallin/SQLiteCodeFirst/tree/Support_Multiple_DotNet_Versions
http://help.appveyor.com/discussions/questions/1196-how-to-build-different-configurations-in-one-job

**Comment by msallin** [comment]
Just released v0.9.5.0
https://www.nuget.org/packages/SQLite.CodeFirst/0.9.5
