### ISSUE TITLE
Annotation for Key an MaxLength

### ISSUE THREAD

**Issue by code1line** [msallin/SQLiteCodeFirst#2]
Something like that should work:

```
[Key]
[MaxLength(31)]
public string Artikelnummer { get; set; }
```

**Comment by msallin** [comment]
Thank you for the suggestion.
They Key Attribute should already working.
I'll add support for the MaxLenght constrain in the next couple of days.

**Comment by code1line** [comment]
[Key] does not work, even not without [MaxLength(31)]

**Comment by msallin** [comment]
_MaxLength:_
You can do something like this in SQLite: `Column NVARCHAR (10)` this will set the maximum length to 10 but SQLite will **not** enforce this value (e.g. by truncating or by throwing an error).
Anyway, I implemented this feature. But I discovered the following behavoir:
If you do something like this:
`[Key]
[MaxLength(5)]
public string LastName { get; set; }`

The SQLite EF provider will ignore the value in `MaxLength` and set the value to 128.
So this also means that each `string` column which is declard as `key` will have the `MaxLength`set to 128.

_Key_
I did some refactorings and changed the code SQLite DDL Code generation so that now the PrimaryKeys are defined with the "PRIMARY KEY" constraint on the table level instead of the column level. This now also makes it possible to have primary key composites. If you whish to use primary key composites, please take into account that you have to annotate the primary key properties also with the `[Column(Order = 1)]` Column order annotation.

See [v0.1-apha.2](https://github.com/msallin/SQLiteCodeFirst/releases/tag/v0.1-apha.2)
