### ISSUE TITLE
Store enum columns (as integer)

### ISSUE THREAD

**Issue by arubiomoreno** [msallin/SQLiteCodeFirst#34]
Enum properties are not stored on the current implementation

``` C#
[Flags]
public enum EAttributes : ulong
{
    // ...
}

public class MyTestTable
{
    public EAttributes Attributes1 { get; set; } // Column not created

    [Column("_attributes2")]
    public EAttributes Attributes2 { get; set; } // Column not created

    [Column("_attributes3", TypeName="integer")]
    public EAttributes Attributes3 { get; set; } // Column not created
}
```

**Comment by pver** [comment]
This is caused by a limitation in Entity Framework itself. As mentioned here: https://msdn.microsoft.com/en-us/data/hh859576 only the following underlying enumeration types are supported: Byte, Int16,  Int32,  Int64 , or SByte.

If you replace the 'ulong' in your enumeration type declaration by 'long' the corresponding column should be created (I've used it like that before):

```
public enum EAttributes : long
{
    // ...
}
```

**Comment by arubiomoreno** [comment]
Very true. I got it working.
Thanks and sorry for raising a wrong issue.

**Comment by pver** [comment]
:+1:  You're welcome! :)
