### ISSUE TITLE
Index naming change to IX_table_column

### ISSUE THREAD

**Issue by xjfnet** [msallin/SQLiteCodeFirst#35]
two table has the same column with [Index] will failed when create databases: the index is alread exsist

class a
{
  [Index]
  public string c {get;set;}
}
class b
{
  [Index]
  public string c {get;set;}
}

**Comment by Rychard** [comment]
This also happens when creating at least _two_ navigation (`virtual`) properties where both the source and destination columns have identical names.

``` csharp

public class Category 
{
    public int CategoryID {get; set;}
    public string CategoryName {get; set;}
}

public class Thing
{
    public int ThingID {get; set;}
    public string ThingName {get; set;}

    // Implicitly creates an index named "IX_CategoryID"
    public int CategoryID {get; set;} 
    public virtual Category Category {get; set;}
}

public class Stuff
{
    public int StuffID {get; set;}
    public string StuffName {get; set;}

    // Attempts to create another index, also named "IX_CategoryID"
    // As this index was already created earlier, we get an error:
    // "index IX_CategoryID already exists"
    public int CategoryID {get; set;} 
    public virtual Category Category {get; set;}
}

```

This occurs because Entity Framework will automatically create an `index` for any column that participates in a foreign-key.  While admittedly, this is a great feature of Entity Framework, I'm finding that it definitely causes an issue.

The workaround (that I hope will only be required temporarily) is to explicitly define the name of the index by decorating the property with the the `IndexAttribute` (`[Index("IX_Item_CategoryID")`).  This seems like it would be easily avoidable at the library level, so I definitely agree with this suggestion.

**Update:** After some testing, I realize that it only occurs when you define multiple tables containing  foreign keys to a common table.  Even then, the error is only encountered if both classes have the same name for the property.  I've updated the example code above, and I was able to reproduce in a fork by adding the above code to the `SQLite.CodeFirst.Console` project and defining the `DbSet<T>` collections in the `FootbalDbContext` class.
