### ISSUE TITLE
Feature suggestion : Add support for Optimistic Concurrency Token / Row Version

### ISSUE THREAD

**Issue by ArnaudDebaene** [msallin/SQLiteCodeFirst#40]
It would be nice to be able to map a Byte[] property that is marked as Row version in the model into the DB.

This should probably be mapped 
- to an integer column, with a 0 or 1 default value
- with a Trigger to update it on update... Something along the line:
  CREATE TRIGGER UpdateMyObjectRowVersion AFTER UPDATE ON MyObject FOR EACH ROW WHEN NEW.RowVersion = OLD.RowVersion
  BEGIN
  UPDATE MyObject SET RowVersion = OLD.RowVersion + 1 WHERE Id = OLD.Id;
  END;

**Comment by msallin** [comment]
Thanks for your Suggestion.
I'll analyze it and let you know about the result.

**Comment by msallin** [comment]
I don't want have to much logic in the default behavoir because it should fit the 99% of the requirements just out of the box.

If I add the ability to define a trigger, with an attribute on a entity, would this solve your problem?

```
[Trigger(Name = "test", When = When.Before, ForEachRow = True, Action = Action.Delete, PreCondition = "xy = xy", Code = "SELECT * FROM xy")]
public class Player 
{
}
```

Would result in the following DDL

```
CREATE TRIGGER test
        BEFORE DELETE
            ON Player
      FOR EACH ROW
          WHEN x = y
BEGIN
    SELECT * FROM X;
END;
```

Let me know what you think about this.

**Comment by msallin** [comment]
Closed due to inactivity.
