### ISSUE TITLE
Error occurred with a console app in VS2015 SP1

### ISSUE THREAD

**Issue by Wakusei** [msallin/SQLiteCodeFirst#54]
I tried SQLite.CodeFirst with the following settings.

```
  <connectionStrings>
    <add name="DefaultConnection" connectionString="Data Source=db.sqlite;" providerName="System.Data.SQLite.EF6"/>
  </connectionStrings>

  <entityFramework>
    <providers>
      <provider invariantName="System.Data.SQLite.EF6" type="System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6" />
    </providers>
  </entityFramework>
```

This caused an error below.

No Entity Framework provider found for the ADO.NET provider with invariant name 'System.Data.SQLite'. Make sure the provider is registered in the 'entityFramework' section of the application config file. See http://go.microsoft.com/fwlink/?LinkId=260882 for more information.

I managed to solve with the invariant name "System.Data.SQLite".

```
  <entityFramework>
    <providers>
      <provider invariantName="System.Data.SQLite" type="System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6" />
    </providers>
  </entityFramework>
```

Which is correct? System.Data.SQLite or the original one?

**Comment by msallin** [comment]
Hi
The error you get is because of EF/SQLite and is not releated with the SQLite.CodeFirst project. But give the config file which comes with the sample project a try:
https://github.com/msallin/SQLiteCodeFirst/blob/master/SQLite.CodeFirst.Console/App.config

Or you can configure the entity framework explicit with C# Code:
swisscoder.ch/2015/12/22/entity-framework-in-code-konfigurieren/

**Comment by Wakusei** [comment]
I'm sorry I thought SQLiteCodeFirst changed the configuration. But it was changed by a package "System.Data.SQLite.EF6".
