### ISSUE TITLE
use initializer through config file

### ISSUE THREAD

**Issue by hpcsc** [msallin/SQLiteCodeFirst#73]
Hi,

Thanks a lot for creating this project, it's very helpful.

At the moment I have a db initializer that inherits from SqliteCreateDatabaseIfNotExists. If I create this custom initializer in db context OnModelCreating() and pass in DbModelBuilder, everything's working fine. However, if I specify this initializer in app.config:

```
<databaseInitializer type="..." />
```

It throws exception, since SqliteCreateDatabaseIfNotExists doesn't have default constructor. Is there anyway to config this in config file? I like the flexibility of config file approach, since I can change initializer without re-compiling the code

Thanks

**Comment by msallin** [comment]
Hello

Unfortunately, the constructor parameter is necessary because of the approach which I use to generate the SQLite-SQL to create the database. So thats the reason why you have to set the initializer in the "OnModelCreating" method of the context, where you have access to the DbModelBuilder.

However you are free to write your own config to determine the initializer to use but you can not use the default configuration to achiev this goal.

Regards
