### ISSUE TITLE
Fails to Initialize Database when indexes are created on field called 'Order'

### ISSUE THREAD

**Issue by jjbutera** [msallin/SQLiteCodeFirst#91]
Seems like a simple fix. I'm guessing column names aren't being bracketed on some SQL create scripts. Error occurs on a column called 'Order' when I annotate an index in my mapping file:

`Property(e => e.Order).IsRequired().HasColumnAnnotation(IndexAnnotation.AnnotationName, new IndexAnnotation(new IndexAttribute("IX_MacroStepOrderDuplicate") { IsUnique = true }));`

The problem goes away if I remove the column annotation.

**Comment by jjbutera** [comment]
Proposed fix in CreateIndexStatement.cs (add brackets around column name):

26: `IEnumerable<string> orderedColumnNames = Columns.OrderBy(c => c.Order).Select(c => $"[{c.Name}]");`

code change:  **$"[{c.Name}]"**

I would think adding brackets around table and column names in all statement builders would be a thorough fix.

**Comment by tbayart** [comment]
Everytime Name is used, it should be between brackets.

**Comment by msallin** [comment]
Hi jjbutera

Thanks for filling the issue.
Actually the names are already escaped but there was a bug in the CreateIndexStatementCollection.GetIndexName().
If a index name was created by the library it was escaped but not if there was one specified manually.

So
return index.Name ?? IndexNameCreator.CreateName(entitySet.ElementType.GetTableName(), property.Name);

Became
return index.Name == null ? IndexNameCreator.CreateName(entitySet.ElementType.GetTableName(), property.Name) : NameCreator.EscapeName(index.

I'm using double quotes ("") instead of square bracket ([])
See http://www.sqlite.org/lang_keywords.html

Regards Marc

**Comment by tbayart** [comment]
Good point Marc for using double quotes 👍 
Thank you for the quick fix
